/** Canonical engagement events that may update user_engagement_stats. */

export const ENGAGEMENT_EVENT_TYPES = {
  AUTH_LOGIN: "AUTH_LOGIN",
  APP_OPEN: "APP_OPEN",
  SESSION_STARTED: "SESSION_STARTED",
  CREATOR_PROFILE_VIEWED: "CREATOR_PROFILE_VIEWED",
  CHAT_STARTED: "CHAT_STARTED",
  CALL_ATTEMPTED: "CALL_ATTEMPTED",
  CALL_COMPLETED: "CALL_COMPLETED",
  RECHARGE_COMPLETED: "RECHARGE_COMPLETED",
};

export const MEANINGFUL_ENGAGEMENT_EVENT_TYPES = new Set([
  ENGAGEMENT_EVENT_TYPES.AUTH_LOGIN,
  ENGAGEMENT_EVENT_TYPES.APP_OPEN,
  ENGAGEMENT_EVENT_TYPES.SESSION_STARTED,
  ENGAGEMENT_EVENT_TYPES.CREATOR_PROFILE_VIEWED,
  ENGAGEMENT_EVENT_TYPES.CHAT_STARTED,
  ENGAGEMENT_EVENT_TYPES.CALL_ATTEMPTED,
  ENGAGEMENT_EVENT_TYPES.CALL_COMPLETED,
  ENGAGEMENT_EVENT_TYPES.RECHARGE_COMPLETED,
]);
