export const FEMALE_ACHIEVEMENT_CATEGORIES = [
  "achievement",
  "honor",
  "activity",
  "premium",
];

export const FEMALE_ACHIEVEMENT_LEVELS = [
  {
    id: "rookie",
    title: "Rookie Creator",
    previewEmoji: "🌱",
    minPoints: 0,
    accentColor: "#81C784",
    description: "Just getting started on your creator journey",
  },
  {
    id: "rising_star",
    title: "Rising Star",
    previewEmoji: "⭐",
    minPoints: 50,
    accentColor: "#FFD54F",
    description: "Building momentum with early wins",
  },
  {
    id: "silver_creator",
    title: "Silver Creator",
    previewEmoji: "🥈",
    minPoints: 150,
    accentColor: "#90A4AE",
    description: "A dependable creator with solid progress",
  },
  {
    id: "gold_creator",
    title: "Gold Creator",
    previewEmoji: "🥇",
    minPoints: 350,
    accentColor: "#FFB300",
    description: "Top-tier creator with impressive achievements",
  },
  {
    id: "diamond_queen",
    title: "Diamond Queen",
    previewEmoji: "💎",
    minPoints: 600,
    accentColor: "#7E57C2",
    description: "Elite creator shining across every category",
  },
  {
    id: "live_legend",
    title: "Live Legend",
    previewEmoji: "👸",
    minPoints: 1000,
    accentColor: "#FF4081",
    description: "Legendary status — the highest creator rank",
  },
];

export const resolveFemaleAchievementLevel = (points = 0) => {
  const safePoints = Math.max(0, Number(points) || 0);
  let currentIndex = 0;

  for (let index = FEMALE_ACHIEVEMENT_LEVELS.length - 1; index >= 0; index -= 1) {
    if (safePoints >= FEMALE_ACHIEVEMENT_LEVELS[index].minPoints) {
      currentIndex = index;
      break;
    }
  }

  const current = FEMALE_ACHIEVEMENT_LEVELS[currentIndex];
  const next = FEMALE_ACHIEVEMENT_LEVELS[currentIndex + 1] ?? null;
  const progressToNext = next
    ? Math.max(
        0,
        Math.min(
          100,
          Math.round(
            ((safePoints - current.minPoints) /
              (next.minPoints - current.minPoints)) *
              100
          )
        )
      )
    : 100;

  return {
    current,
    next,
    points: safePoints,
    progressToNext,
    isMaxLevel: !next,
  };
};

export const DEFAULT_FEMALE_ACHIEVEMENT_BADGES = [
  {
    id: "first_call",
    title: "First Call",
    category: "achievement",
    previewEmoji: "📞",
    iconKey: "phone",
    description: "Complete your first call",
    points: 10,
    requirementType: "calls",
    requirementValue: 1,
    sortOrder: 1,
  },
  {
    id: "call_star_1",
    title: "Call Star I",
    category: "achievement",
    previewEmoji: "⭐",
    iconKey: "star",
    description: "Receive 10 calls",
    points: 20,
    requirementType: "calls",
    requirementValue: 10,
    sortOrder: 2,
  },
  {
    id: "call_star_2",
    title: "Call Star II",
    category: "achievement",
    previewEmoji: "🌟",
    iconKey: "star-four-points",
    description: "Receive 50 calls",
    points: 40,
    requirementType: "calls",
    requirementValue: 50,
    sortOrder: 3,
  },
  {
    id: "call_star_3",
    title: "Call Star III",
    category: "achievement",
    previewEmoji: "💫",
    iconKey: "star-shooting",
    description: "Receive 100 calls",
    points: 80,
    requirementType: "calls",
    requirementValue: 100,
    sortOrder: 4,
  },
  {
    id: "gold_starter",
    title: "Gold Starter",
    category: "achievement",
    previewEmoji: "🪙",
    iconKey: "circle-multiple",
    description: "Earn 100 gold",
    points: 15,
    requirementType: "gold",
    requirementValue: 100,
    sortOrder: 5,
  },
  {
    id: "gold_hunter",
    title: "Gold Hunter",
    category: "achievement",
    previewEmoji: "💰",
    iconKey: "cash-multiple",
    description: "Earn 1,000 gold",
    points: 35,
    requirementType: "gold",
    requirementValue: 1000,
    sortOrder: 6,
  },
  {
    id: "gold_queen",
    title: "Gold Queen",
    category: "achievement",
    previewEmoji: "👑",
    iconKey: "crown",
    description: "Earn 10,000 gold",
    points: 100,
    requirementType: "gold",
    requirementValue: 10000,
    sortOrder: 7,
  },
  {
    id: "time_keeper",
    title: "Time Keeper",
    category: "achievement",
    previewEmoji: "⏱",
    iconKey: "clock-outline",
    description: "Spend 60 call minutes",
    points: 20,
    requirementType: "minutes",
    requirementValue: 60,
    sortOrder: 8,
  },
  {
    id: "marathon_creator",
    title: "Marathon Creator",
    category: "achievement",
    previewEmoji: "🏃",
    iconKey: "run-fast",
    description: "Spend 500 call minutes",
    points: 60,
    requirementType: "minutes",
    requirementValue: 500,
    sortOrder: 9,
  },
  {
    id: "verified_creator",
    title: "Verified Creator",
    category: "achievement",
    previewEmoji: "✅",
    iconKey: "check-decagram",
    description: "Get verified as a creator",
    points: 50,
    requirementType: "verified",
    requirementValue: 1,
    sortOrder: 10,
  },
  {
    id: "level_riser",
    title: "Level Riser",
    category: "achievement",
    previewEmoji: "📈",
    iconKey: "trending-up",
    description: "Reach creator level 3",
    points: 30,
    requirementType: "level",
    requirementValue: 3,
    sortOrder: 11,
  },
  {
    id: "top_creator",
    title: "Top Creator",
    category: "achievement",
    previewEmoji: "🏆",
    iconKey: "trophy",
    description: "Reach creator level 7",
    points: 120,
    requirementType: "level",
    requirementValue: 7,
    sortOrder: 12,
  },
  {
    id: "gift_guardian",
    title: "Gift Guardian",
    category: "honor",
    previewEmoji: "🎁",
    iconKey: "gift",
    description: "Receive 5 gifts on calls",
    points: 25,
    requirementType: "gifts",
    requirementValue: 5,
    sortOrder: 13,
  },
  {
    id: "room_queen",
    title: "Room Queen",
    category: "honor",
    previewEmoji: "🎤",
    iconKey: "microphone-variant",
    description: "Receive 25 calls",
    points: 45,
    requirementType: "calls",
    requirementValue: 25,
    sortOrder: 14,
  },
  {
    id: "super_idol",
    title: "Super Idol",
    category: "honor",
    previewEmoji: "💖",
    iconKey: "heart",
    description: "Reach creator level 5",
    points: 70,
    requirementType: "level",
    requirementValue: 5,
    sortOrder: 15,
  },
  {
    id: "top_protector",
    title: "Top Protector",
    category: "honor",
    previewEmoji: "🛡",
    iconKey: "shield-star",
    description: "Receive 20 gifts on calls",
    points: 90,
    requirementType: "gifts",
    requirementValue: 20,
    sortOrder: 16,
  },
  {
    id: "daily_warrior",
    title: "Daily Warrior",
    category: "activity",
    previewEmoji: "🔥",
    iconKey: "fire",
    description: "Claim 3 daily tasks",
    points: 20,
    requirementType: "tasks",
    requirementValue: 3,
    sortOrder: 17,
  },
  {
    id: "task_master",
    title: "Task Master",
    category: "activity",
    previewEmoji: "✨",
    iconKey: "checkbox-marked-circle",
    description: "Claim 10 tasks",
    points: 50,
    requirementType: "tasks",
    requirementValue: 10,
    sortOrder: 18,
  },
  {
    id: "online_hero",
    title: "Online Hero",
    category: "activity",
    previewEmoji: "🟢",
    iconKey: "access-point",
    description: "Stay online for 300 minutes total",
    points: 40,
    requirementType: "online_minutes",
    requirementValue: 300,
    sortOrder: 19,
  },
  {
    id: "live_legend",
    title: "Live Legend",
    category: "activity",
    previewEmoji: "📡",
    iconKey: "broadcast",
    description: "Stay online for 1,000 minutes total",
    points: 100,
    requirementType: "online_minutes",
    requirementValue: 1000,
    sortOrder: 20,
  },
  {
    id: "rocket_queen",
    title: "Rocket Queen",
    category: "honor",
    previewEmoji: "🚀",
    iconKey: "rocket-launch",
    description: "Receive 200 calls",
    points: 110,
    requirementType: "calls",
    requirementValue: 200,
    sortOrder: 21,
  },
  {
    id: "copper_spacer",
    title: "Copper Spacer",
    category: "activity",
    previewEmoji: "🛸",
    iconKey: "rocket-outline",
    description: "Stay online for 30 minutes total",
    points: 12,
    requirementType: "online_minutes",
    requirementValue: 30,
    sortOrder: 22,
  },
  {
    id: "voice_enchantress",
    title: "Voice Enchantress",
    category: "achievement",
    previewEmoji: "🎙",
    iconKey: "microphone",
    description: "Spend 150 call minutes",
    points: 45,
    requirementType: "minutes",
    requirementValue: 150,
    sortOrder: 23,
  },
  {
    id: "heart_magnet",
    title: "Heart Magnet",
    category: "honor",
    previewEmoji: "💕",
    iconKey: "heart-multiple",
    description: "Receive 50 gifts on calls",
    points: 75,
    requirementType: "gifts",
    requirementValue: 50,
    sortOrder: 24,
  },
  {
    id: "streak_champion",
    title: "Streak Champion",
    category: "activity",
    previewEmoji: "🔥",
    iconKey: "fire-circle",
    description: "Claim 25 tasks",
    points: 85,
    requirementType: "tasks",
    requirementValue: 25,
    sortOrder: 25,
  },
  {
    id: "moonlight_queen",
    title: "Moonlight Queen",
    category: "activity",
    previewEmoji: "🌙",
    iconKey: "weather-night",
    description: "Stay online for 2,000 minutes total",
    points: 130,
    requirementType: "online_minutes",
    requirementValue: 2000,
    sortOrder: 26,
  },
  {
    id: "diamond_earner",
    title: "Diamond Earner",
    category: "achievement",
    previewEmoji: "💎",
    iconKey: "diamond-stone",
    description: "Earn 50,000 gold",
    points: 200,
    requirementType: "gold",
    requirementValue: 50000,
    sortOrder: 27,
  },
  {
    id: "fan_favorite",
    title: "Fan Favorite",
    category: "honor",
    previewEmoji: "❤️",
    iconKey: "heart-circle",
    description: "Receive 500 calls",
    points: 160,
    requirementType: "calls",
    requirementValue: 500,
    sortOrder: 28,
  },
  {
    id: "super_host",
    title: "Super Host",
    category: "achievement",
    previewEmoji: "🎬",
    iconKey: "movie-open-star",
    description: "Spend 1,000 call minutes",
    points: 140,
    requirementType: "minutes",
    requirementValue: 1000,
    sortOrder: 29,
  },
  {
    id: "platinum_idol",
    title: "Platinum Idol",
    category: "honor",
    previewEmoji: "💜",
    iconKey: "star-face",
    description: "Reach creator level 10",
    points: 180,
    requirementType: "level",
    requirementValue: 10,
    sortOrder: 30,
  },
  {
    id: "charm_guardian",
    title: "Charm Guardian",
    category: "honor",
    previewEmoji: "🛡",
    iconKey: "shield-crown",
    description: "Receive 100 gifts on calls",
    points: 150,
    requirementType: "gifts",
    requirementValue: 100,
    sortOrder: 31,
  },
  {
    id: "first_five",
    title: "First Five",
    category: "achievement",
    previewEmoji: "🎯",
    iconKey: "target",
    description: "Receive 5 calls",
    points: 12,
    requirementType: "calls",
    requirementValue: 5,
    sortOrder: 32,
  },
  {
    id: "call_veteran",
    title: "Call Veteran",
    category: "achievement",
    previewEmoji: "📺",
    iconKey: "video-vintage",
    description: "Receive 250 calls",
    points: 130,
    requirementType: "calls",
    requirementValue: 250,
    sortOrder: 33,
  },
  {
    id: "call_immortal",
    title: "Call Immortal",
    category: "achievement",
    previewEmoji: "🌠",
    iconKey: "weather-night",
    description: "Receive 1,000 calls",
    points: 220,
    requirementType: "calls",
    requirementValue: 1000,
    sortOrder: 34,
  },
  {
    id: "gold_rush",
    title: "Gold Rush",
    category: "achievement",
    previewEmoji: "✨",
    iconKey: "shimmer",
    description: "Earn 500 gold",
    points: 22,
    requirementType: "gold",
    requirementValue: 500,
    sortOrder: 35,
  },
  {
    id: "gold_empire",
    title: "Gold Empire",
    category: "achievement",
    previewEmoji: "🏦",
    iconKey: "bank",
    description: "Earn 25,000 gold",
    points: 160,
    requirementType: "gold",
    requirementValue: 25000,
    sortOrder: 36,
  },
  {
    id: "gold_legend",
    title: "Gold Legend",
    category: "achievement",
    previewEmoji: "🏆",
    iconKey: "trophy-award",
    description: "Earn 100,000 gold",
    points: 250,
    requirementType: "gold",
    requirementValue: 100000,
    sortOrder: 37,
  },
  {
    id: "talk_time_pro",
    title: "Talk Time Pro",
    category: "achievement",
    previewEmoji: "💬",
    iconKey: "message-text",
    description: "Spend 30 call minutes",
    points: 14,
    requirementType: "minutes",
    requirementValue: 30,
    sortOrder: 38,
  },
  {
    id: "endless_chat",
    title: "Endless Chat",
    category: "achievement",
    previewEmoji: "🌙",
    iconKey: "chat-processing",
    description: "Spend 2,500 call minutes",
    points: 190,
    requirementType: "minutes",
    requirementValue: 2500,
    sortOrder: 39,
  },
  {
    id: "level_spark",
    title: "Level Spark",
    category: "achievement",
    previewEmoji: "⚡",
    iconKey: "lightning-bolt",
    description: "Reach creator level 2",
    points: 18,
    requirementType: "level",
    requirementValue: 2,
    sortOrder: 40,
  },
  {
    id: "elite_creator",
    title: "Elite Creator",
    category: "achievement",
    previewEmoji: "💠",
    iconKey: "diamond",
    description: "Reach creator level 12",
    points: 200,
    requirementType: "level",
    requirementValue: 12,
    sortOrder: 41,
  },
  {
    id: "first_spark",
    title: "First Spark",
    category: "honor",
    previewEmoji: "🎀",
    iconKey: "bow-tie",
    description: "Receive your first gift on a call",
    points: 12,
    requirementType: "gifts",
    requirementValue: 1,
    sortOrder: 42,
  },
  {
    id: "beloved_star",
    title: "Beloved Star",
    category: "honor",
    previewEmoji: "🌸",
    iconKey: "flower",
    description: "Receive 10 gifts on calls",
    points: 35,
    requirementType: "gifts",
    requirementValue: 10,
    sortOrder: 43,
  },
  {
    id: "treasured_idol",
    title: "Treasured Idol",
    category: "honor",
    previewEmoji: "💎",
    iconKey: "gem",
    description: "Receive 200 gifts on calls",
    points: 170,
    requirementType: "gifts",
    requirementValue: 200,
    sortOrder: 44,
  },
  {
    id: "legend_muse",
    title: "Legend Muse",
    category: "honor",
    previewEmoji: "🦄",
    iconKey: "unicorn",
    description: "Receive 500 gifts on calls",
    points: 240,
    requirementType: "gifts",
    requirementValue: 500,
    sortOrder: 45,
  },
  {
    id: "crowd_magnet",
    title: "Crowd Magnet",
    category: "honor",
    previewEmoji: "🤩",
    iconKey: "account-heart",
    description: "Receive 75 calls",
    points: 65,
    requirementType: "calls",
    requirementValue: 75,
    sortOrder: 46,
  },
  {
    id: "arena_empress",
    title: "Arena Empress",
    category: "honor",
    previewEmoji: "🏰",
    iconKey: "castle",
    description: "Receive 1,000 calls",
    points: 210,
    requirementType: "calls",
    requirementValue: 1000,
    sortOrder: 47,
  },
  {
    id: "noble_star",
    title: "Noble Star",
    category: "honor",
    previewEmoji: "🌠",
    iconKey: "star-circle",
    description: "Reach creator level 8",
    points: 140,
    requirementType: "level",
    requirementValue: 8,
    sortOrder: 48,
  },
  {
    id: "celestial_queen",
    title: "Celestial Queen",
    category: "honor",
    previewEmoji: "🌌",
    iconKey: "weather-night-partly-cloudy",
    description: "Reach creator level 15",
    points: 230,
    requirementType: "level",
    requirementValue: 15,
    sortOrder: 49,
  },
  {
    id: "first_mission",
    title: "First Mission",
    category: "activity",
    previewEmoji: "✅",
    iconKey: "check",
    description: "Claim your first task",
    points: 10,
    requirementType: "tasks",
    requirementValue: 1,
    sortOrder: 50,
  },
  {
    id: "weekly_hustle",
    title: "Weekly Hustle",
    category: "activity",
    previewEmoji: "📅",
    iconKey: "calendar-check",
    description: "Claim 7 tasks",
    points: 28,
    requirementType: "tasks",
    requirementValue: 7,
    sortOrder: 51,
  },
  {
    id: "mission_ace",
    title: "Mission Ace",
    category: "activity",
    previewEmoji: "🎲",
    iconKey: "dice-5",
    description: "Claim 50 tasks",
    points: 110,
    requirementType: "tasks",
    requirementValue: 50,
    sortOrder: 52,
  },
  {
    id: "task_legend",
    title: "Task Legend",
    category: "activity",
    previewEmoji: "🏅",
    iconKey: "medal-outline",
    description: "Claim 100 tasks",
    points: 180,
    requirementType: "tasks",
    requirementValue: 100,
    sortOrder: 53,
  },
  {
    id: "quick_online",
    title: "Quick Online",
    category: "activity",
    previewEmoji: "⏱",
    iconKey: "timer-outline",
    description: "Stay online for 10 minutes total",
    points: 8,
    requirementType: "online_minutes",
    requirementValue: 10,
    sortOrder: 54,
  },
  {
    id: "shift_hero",
    title: "Shift Hero",
    category: "activity",
    previewEmoji: "🌞",
    iconKey: "white-balance-sunny",
    description: "Stay online for 120 minutes total",
    points: 28,
    requirementType: "online_minutes",
    requirementValue: 120,
    sortOrder: 55,
  },
  {
    id: "always_live",
    title: "Always Live",
    category: "activity",
    previewEmoji: "📡",
    iconKey: "access-point-network",
    description: "Stay online for 750 minutes total",
    points: 80,
    requirementType: "online_minutes",
    requirementValue: 750,
    sortOrder: 56,
  },
  {
    id: "eternal_live",
    title: "Eternal Live",
    category: "activity",
    previewEmoji: "♾️",
    iconKey: "infinity",
    description: "Stay online for 5,000 minutes total",
    points: 200,
    requirementType: "online_minutes",
    requirementValue: 5000,
    sortOrder: 57,
  },
  {
    id: "vip_crown",
    title: "VIP Crown",
    category: "premium",
    previewEmoji: "👑",
    iconKey: "crown",
    description: "Unlock VIP status at creator level 20",
    points: 300,
    requirementType: "level",
    requirementValue: 20,
    sortOrder: 58,
  },
  {
    id: "golden_throne",
    title: "Golden Throne",
    category: "premium",
    previewEmoji: "🏰",
    iconKey: "castle",
    description: "Earn 250,000 gold as a premium creator",
    points: 320,
    requirementType: "gold",
    requirementValue: 250000,
    sortOrder: 59,
  },
  {
    id: "heart_empress",
    title: "Heart Empress",
    category: "premium",
    previewEmoji: "💝",
    iconKey: "heart-box",
    description: "Receive 1,000 premium gifts on calls",
    points: 300,
    requirementType: "gifts",
    requirementValue: 1000,
    sortOrder: 60,
  },
  {
    id: "call_sovereign",
    title: "Call Sovereign",
    category: "premium",
    previewEmoji: "👸",
    iconKey: "account-star",
    description: "Receive 2,500 calls as a premium host",
    points: 310,
    requirementType: "calls",
    requirementValue: 2500,
    sortOrder: 61,
  },
  {
    id: "velvet_voice",
    title: "Velvet Voice",
    category: "premium",
    previewEmoji: "🔮",
    iconKey: "crystal-ball",
    description: "Spend 10,000 premium call minutes",
    points: 280,
    requirementType: "minutes",
    requirementValue: 10000,
    sortOrder: 62,
  },
  {
    id: "midnight_prestige",
    title: "Midnight Prestige",
    category: "premium",
    previewEmoji: "🌃",
    iconKey: "weather-night",
    description: "Stay online for 10,000 premium minutes",
    points: 270,
    requirementType: "online_minutes",
    requirementValue: 10000,
    sortOrder: 63,
  },
  {
    id: "peacock_royale",
    title: "Peacock Royale",
    category: "premium",
    previewEmoji: "🦚",
    iconKey: "feather",
    description: "Receive 1,500 exclusive gifts",
    points: 290,
    requirementType: "gifts",
    requirementValue: 1500,
    sortOrder: 64,
  },
  {
    id: "aurora_queen",
    title: "Aurora Queen",
    category: "premium",
    previewEmoji: "🌌",
    iconKey: "weather-night-partly-cloudy",
    description: "Reach creator level 25",
    points: 350,
    requirementType: "level",
    requirementValue: 25,
    sortOrder: 65,
  },
  {
    id: "gilded_star",
    title: "Gilded Star",
    category: "premium",
    previewEmoji: "🌟",
    iconKey: "star-four-points",
    description: "Earn 500,000 gold",
    points: 400,
    requirementType: "gold",
    requirementValue: 500000,
    sortOrder: 66,
  },
  {
    id: "swan_palace",
    title: "Swan Palace",
    category: "premium",
    previewEmoji: "🦢",
    iconKey: "bird",
    description: "Receive 5,000 calls",
    points: 360,
    requirementType: "calls",
    requirementValue: 5000,
    sortOrder: 67,
  },
  {
    id: "phoenix_vip",
    title: "Phoenix VIP",
    category: "premium",
    previewEmoji: "🔥",
    iconKey: "fire",
    description: "Stay online for 20,000 premium minutes",
    points: 380,
    requirementType: "online_minutes",
    requirementValue: 20000,
    sortOrder: 68,
  },
  {
    id: "crystal_oracle",
    title: "Crystal Oracle",
    category: "premium",
    previewEmoji: "🪞",
    iconKey: "mirror",
    description: "Spend 20,000 call minutes",
    points: 340,
    requirementType: "minutes",
    requirementValue: 20000,
    sortOrder: 69,
  },
];

export const MAX_WORN_ACHIEVEMENT_BADGES = 3;
