export const MALE_ACHIEVEMENT_CATEGORIES = [
  "achievement",
  "honor",
  "activity",
  "premium",
];

export const MALE_ACHIEVEMENT_LEVELS = [
  {
    id: "new_member",
    title: "New Member",
    previewEmoji: "🌱",
    minPoints: 0,
    accentColor: "#81C784",
    description: "Just getting started on your supporter journey",
  },
  {
    id: "bronze_supporter",
    title: "Bronze Supporter",
    previewEmoji: "🥉",
    minPoints: 50,
    accentColor: "#FFB74D",
    description: "Building momentum with early wins",
  },
  {
    id: "silver_supporter",
    title: "Silver Supporter",
    previewEmoji: "🥈",
    minPoints: 150,
    accentColor: "#90A4AE",
    description: "A dependable supporter with solid progress",
  },
  {
    id: "gold_patron",
    title: "Gold Patron",
    previewEmoji: "🥇",
    minPoints: 350,
    accentColor: "#FFB300",
    description: "Top-tier supporter with impressive achievements",
  },
  {
    id: "diamond_patron",
    title: "Diamond Patron",
    previewEmoji: "💎",
    minPoints: 600,
    accentColor: "#7E57C2",
    description: "Elite supporter shining across every category",
  },
  {
    id: "legend_supporter",
    title: "Legend Supporter",
    previewEmoji: "👑",
    minPoints: 1000,
    accentColor: "#FF4081",
    description: "Legendary status — the highest supporter rank",
  },
];

export const resolveMaleAchievementLevel = (points = 0) => {
  const safePoints = Math.max(0, Number(points) || 0);
  let currentIndex = 0;

  for (let index = MALE_ACHIEVEMENT_LEVELS.length - 1; index >= 0; index -= 1) {
    if (safePoints >= MALE_ACHIEVEMENT_LEVELS[index].minPoints) {
      currentIndex = index;
      break;
    }
  }

  const current = MALE_ACHIEVEMENT_LEVELS[currentIndex];
  const next = MALE_ACHIEVEMENT_LEVELS[currentIndex + 1] ?? null;
  const progressToNext = next
    ? Math.max(
        0,
        Math.min(
          100,
          Math.round(
            ((safePoints - current.minPoints) /
              (next.minPoints - current.minPoints)) *
              100
          )
        )
      )
    : 100;

  return {
    current,
    next,
    points: safePoints,
    progressToNext,
    isMaxLevel: !next,
  };
};

export const DEFAULT_MALE_ACHIEVEMENT_BADGES = [
  {
    id: "male_first_call",
    title: "First Call",
    category: "achievement",
    previewEmoji: "📞",
    iconKey: "phone",
    description: "Complete your first call",
    points: 10,
    requirementType: "calls",
    requirementValue: 1,
    sortOrder: 1,
  },
  {
    id: "male_call_star_1",
    title: "Call Star I",
    category: "achievement",
    previewEmoji: "⭐",
    iconKey: "star",
    description: "Make 10 calls",
    points: 20,
    requirementType: "calls",
    requirementValue: 10,
    sortOrder: 2,
  },
  {
    id: "male_call_star_2",
    title: "Call Star II",
    category: "achievement",
    previewEmoji: "🌟",
    iconKey: "star-four-points",
    description: "Make 50 calls",
    points: 40,
    requirementType: "calls",
    requirementValue: 50,
    sortOrder: 3,
  },
  {
    id: "male_call_star_3",
    title: "Call Star III",
    category: "achievement",
    previewEmoji: "💫",
    iconKey: "star-shooting",
    description: "Make 100 calls",
    points: 80,
    requirementType: "calls",
    requirementValue: 100,
    sortOrder: 4,
  },
  {
    id: "male_gold_starter",
    title: "Gold Starter",
    category: "achievement",
    previewEmoji: "🪙",
    iconKey: "circle-multiple",
    description: "Spend 100 gold on calls",
    points: 15,
    requirementType: "gold_spent",
    requirementValue: 100,
    sortOrder: 5,
  },
  {
    id: "male_gold_hunter",
    title: "Gold Hunter",
    category: "achievement",
    previewEmoji: "💰",
    iconKey: "cash-multiple",
    description: "Spend 1,000 gold on calls",
    points: 35,
    requirementType: "gold_spent",
    requirementValue: 1000,
    sortOrder: 6,
  },
  {
    id: "male_gold_king",
    title: "Gold King",
    category: "achievement",
    previewEmoji: "👑",
    iconKey: "crown",
    description: "Spend 10,000 gold on calls",
    points: 100,
    requirementType: "gold_spent",
    requirementValue: 10000,
    sortOrder: 7,
  },
  {
    id: "male_time_keeper",
    title: "Time Keeper",
    category: "achievement",
    previewEmoji: "⏱",
    iconKey: "clock-outline",
    description: "Spend 60 call minutes",
    points: 20,
    requirementType: "minutes",
    requirementValue: 60,
    sortOrder: 8,
  },
  {
    id: "male_marathon_caller",
    title: "Marathon Caller",
    category: "achievement",
    previewEmoji: "🏃",
    iconKey: "run-fast",
    description: "Spend 500 call minutes",
    points: 60,
    requirementType: "minutes",
    requirementValue: 500,
    sortOrder: 9,
  },
  {
    id: "male_verified",
    title: "Verified Member",
    category: "achievement",
    previewEmoji: "✅",
    iconKey: "check-decagram",
    description: "Get verified on the platform",
    points: 50,
    requirementType: "verified",
    requirementValue: 1,
    sortOrder: 10,
  },
  {
    id: "male_level_riser",
    title: "Level Riser",
    category: "achievement",
    previewEmoji: "📈",
    iconKey: "trending-up",
    description: "Reach level 3",
    points: 30,
    requirementType: "level",
    requirementValue: 3,
    sortOrder: 11,
  },
  {
    id: "male_top_supporter",
    title: "Top Supporter",
    category: "achievement",
    previewEmoji: "🏆",
    iconKey: "trophy",
    description: "Reach level 7",
    points: 120,
    requirementType: "level",
    requirementValue: 7,
    sortOrder: 12,
  },
  {
    id: "male_gift_giver",
    title: "Gift Giver",
    category: "honor",
    previewEmoji: "🎁",
    iconKey: "gift",
    description: "Send 5 gifts on calls",
    points: 25,
    requirementType: "gifts",
    requirementValue: 5,
    sortOrder: 13,
  },
  {
    id: "male_generous_heart",
    title: "Generous Heart",
    category: "honor",
    previewEmoji: "💖",
    iconKey: "heart",
    description: "Send 25 gifts on calls",
    points: 70,
    requirementType: "gifts",
    requirementValue: 25,
    sortOrder: 14,
  },
  {
    id: "male_super_gifter",
    title: "Super Gifter",
    category: "honor",
    previewEmoji: "🛡",
    iconKey: "shield-star",
    description: "Send 50 gifts on calls",
    points: 90,
    requirementType: "gifts",
    requirementValue: 50,
    sortOrder: 15,
  },
  {
    id: "male_fan_collector",
    title: "Fan Collector",
    category: "honor",
    previewEmoji: "❤️",
    iconKey: "heart-circle",
    description: "Add 10 creators to favorites",
    points: 45,
    requirementType: "favorites",
    requirementValue: 10,
    sortOrder: 16,
  },
  {
    id: "male_first_recharge",
    title: "First Recharge",
    category: "activity",
    previewEmoji: "💳",
    iconKey: "credit-card",
    description: "Complete your first recharge",
    points: 20,
    requirementType: "recharges",
    requirementValue: 1,
    sortOrder: 17,
  },
  {
    id: "male_recharge_pro",
    title: "Recharge Pro",
    category: "activity",
    previewEmoji: "🔥",
    iconKey: "fire",
    description: "Complete 5 recharges",
    points: 50,
    requirementType: "recharges",
    requirementValue: 5,
    sortOrder: 18,
  },
  {
    id: "male_voice_enthusiast",
    title: "Voice Enthusiast",
    category: "activity",
    previewEmoji: "🎙",
    iconKey: "microphone",
    description: "Spend 150 call minutes",
    points: 45,
    requirementType: "minutes",
    requirementValue: 150,
    sortOrder: 19,
  },
  {
    id: "male_platinum_patron",
    title: "Platinum Patron",
    category: "honor",
    previewEmoji: "💜",
    iconKey: "star-face",
    description: "Reach level 10",
    points: 180,
    requirementType: "level",
    requirementValue: 10,
    sortOrder: 20,
  },
  {
    id: "male_first_five",
    title: "First Five",
    category: "achievement",
    previewEmoji: "🎯",
    iconKey: "target",
    description: "Make 5 calls",
    points: 12,
    requirementType: "calls",
    requirementValue: 5,
    sortOrder: 21,
  },
  {
    id: "male_call_veteran",
    title: "Call Veteran",
    category: "achievement",
    previewEmoji: "📺",
    iconKey: "video-vintage",
    description: "Make 250 calls",
    points: 130,
    requirementType: "calls",
    requirementValue: 250,
    sortOrder: 22,
  },
  {
    id: "male_call_immortal",
    title: "Call Immortal",
    category: "achievement",
    previewEmoji: "🌠",
    iconKey: "weather-night",
    description: "Make 1,000 calls",
    points: 220,
    requirementType: "calls",
    requirementValue: 1000,
    sortOrder: 23,
  },
  {
    id: "male_gold_rush",
    title: "Gold Rush",
    category: "achievement",
    previewEmoji: "✨",
    iconKey: "shimmer",
    description: "Spend 500 gold on calls",
    points: 22,
    requirementType: "gold_spent",
    requirementValue: 500,
    sortOrder: 24,
  },
  {
    id: "male_gold_empire",
    title: "Gold Empire",
    category: "achievement",
    previewEmoji: "🏦",
    iconKey: "bank",
    description: "Spend 25,000 gold on calls",
    points: 160,
    requirementType: "gold_spent",
    requirementValue: 25000,
    sortOrder: 25,
  },
  {
    id: "male_gold_legend",
    title: "Gold Legend",
    category: "achievement",
    previewEmoji: "🏆",
    iconKey: "trophy-award",
    description: "Spend 100,000 gold on calls",
    points: 250,
    requirementType: "gold_spent",
    requirementValue: 100000,
    sortOrder: 26,
  },
  {
    id: "male_talk_time_pro",
    title: "Talk Time Pro",
    category: "achievement",
    previewEmoji: "💬",
    iconKey: "message-text",
    description: "Spend 30 call minutes",
    points: 14,
    requirementType: "minutes",
    requirementValue: 30,
    sortOrder: 27,
  },
  {
    id: "male_endless_chat",
    title: "Endless Chat",
    category: "achievement",
    previewEmoji: "🌙",
    iconKey: "chat-processing",
    description: "Spend 2,500 call minutes",
    points: 190,
    requirementType: "minutes",
    requirementValue: 2500,
    sortOrder: 28,
  },
  {
    id: "male_level_spark",
    title: "Level Spark",
    category: "achievement",
    previewEmoji: "⚡",
    iconKey: "lightning-bolt",
    description: "Reach level 2",
    points: 18,
    requirementType: "level",
    requirementValue: 2,
    sortOrder: 29,
  },
  {
    id: "male_elite_supporter",
    title: "Elite Supporter",
    category: "achievement",
    previewEmoji: "💠",
    iconKey: "diamond",
    description: "Reach level 12",
    points: 200,
    requirementType: "level",
    requirementValue: 12,
    sortOrder: 30,
  },
  {
    id: "male_first_spark",
    title: "First Spark",
    category: "honor",
    previewEmoji: "🎀",
    iconKey: "bow-tie",
    description: "Send your first gift on a call",
    points: 12,
    requirementType: "gifts",
    requirementValue: 1,
    sortOrder: 31,
  },
  {
    id: "male_beloved_star",
    title: "Beloved Star",
    category: "honor",
    previewEmoji: "🌸",
    iconKey: "flower",
    description: "Send 10 gifts on calls",
    points: 35,
    requirementType: "gifts",
    requirementValue: 10,
    sortOrder: 32,
  },
  {
    id: "male_treasured_patron",
    title: "Treasured Patron",
    category: "honor",
    previewEmoji: "💎",
    iconKey: "gem",
    description: "Send 200 gifts on calls",
    points: 170,
    requirementType: "gifts",
    requirementValue: 200,
    sortOrder: 33,
  },
  {
    id: "male_legend_muse",
    title: "Legend Muse",
    category: "honor",
    previewEmoji: "🦄",
    iconKey: "unicorn",
    description: "Send 500 gifts on calls",
    points: 240,
    requirementType: "gifts",
    requirementValue: 500,
    sortOrder: 34,
  },
  {
    id: "male_crowd_magnet",
    title: "Crowd Magnet",
    category: "honor",
    previewEmoji: "🤩",
    iconKey: "account-heart",
    description: "Add 25 creators to favorites",
    points: 65,
    requirementType: "favorites",
    requirementValue: 25,
    sortOrder: 35,
  },
  {
    id: "male_arena_king",
    title: "Arena King",
    category: "honor",
    previewEmoji: "🏰",
    iconKey: "castle",
    description: "Make 1,000 calls",
    points: 210,
    requirementType: "calls",
    requirementValue: 1000,
    sortOrder: 36,
  },
  {
    id: "male_noble_star",
    title: "Noble Star",
    category: "honor",
    previewEmoji: "🌠",
    iconKey: "star-circle",
    description: "Reach level 8",
    points: 140,
    requirementType: "level",
    requirementValue: 8,
    sortOrder: 37,
  },
  {
    id: "male_celestial_king",
    title: "Celestial King",
    category: "honor",
    previewEmoji: "🌌",
    iconKey: "weather-night-partly-cloudy",
    description: "Reach level 15",
    points: 230,
    requirementType: "level",
    requirementValue: 15,
    sortOrder: 38,
  },
  {
    id: "male_second_recharge",
    title: "Wallet Warmup",
    category: "activity",
    previewEmoji: "🪙",
    iconKey: "wallet",
    description: "Complete 2 recharges",
    points: 28,
    requirementType: "recharges",
    requirementValue: 2,
    sortOrder: 39,
  },
  {
    id: "male_recharge_ace",
    title: "Recharge Ace",
    category: "activity",
    previewEmoji: "💳",
    iconKey: "credit-card-check",
    description: "Complete 10 recharges",
    points: 80,
    requirementType: "recharges",
    requirementValue: 10,
    sortOrder: 40,
  },
  {
    id: "male_recharge_legend",
    title: "Recharge Legend",
    category: "activity",
    previewEmoji: "💎",
    iconKey: "diamond-stone",
    description: "Complete 25 recharges",
    points: 150,
    requirementType: "recharges",
    requirementValue: 25,
    sortOrder: 41,
  },
  {
    id: "male_quick_talk",
    title: "Quick Talk",
    category: "activity",
    previewEmoji: "⏱",
    iconKey: "timer-outline",
    description: "Spend 10 call minutes",
    points: 8,
    requirementType: "minutes",
    requirementValue: 10,
    sortOrder: 42,
  },
  {
    id: "male_night_caller",
    title: "Night Caller",
    category: "activity",
    previewEmoji: "🌙",
    iconKey: "weather-night",
    description: "Spend 300 call minutes",
    points: 70,
    requirementType: "minutes",
    requirementValue: 300,
    sortOrder: 43,
  },
  {
    id: "male_loyal_fan",
    title: "Loyal Fan",
    category: "activity",
    previewEmoji: "💗",
    iconKey: "heart-outline",
    description: "Add 3 creators to favorites",
    points: 18,
    requirementType: "favorites",
    requirementValue: 3,
    sortOrder: 44,
  },
  {
    id: "male_super_fan",
    title: "Super Fan",
    category: "activity",
    previewEmoji: "🔥",
    iconKey: "fire",
    description: "Add 50 creators to favorites",
    points: 120,
    requirementType: "favorites",
    requirementValue: 50,
    sortOrder: 45,
  },
  {
    id: "male_call_habit",
    title: "Call Habit",
    category: "activity",
    previewEmoji: "📅",
    iconKey: "calendar-check",
    description: "Make 25 calls",
    points: 40,
    requirementType: "calls",
    requirementValue: 25,
    sortOrder: 46,
  },
  {
    id: "male_vip_crown",
    title: "VIP Crown",
    category: "premium",
    previewEmoji: "👑",
    iconKey: "crown",
    description: "Unlock VIP status at level 20",
    points: 300,
    requirementType: "level",
    requirementValue: 20,
    sortOrder: 47,
  },
  {
    id: "male_golden_vault",
    title: "Golden Vault",
    category: "premium",
    previewEmoji: "🏦",
    iconKey: "bank",
    description: "Spend 250,000 gold on calls",
    points: 320,
    requirementType: "gold_spent",
    requirementValue: 250000,
    sortOrder: 48,
  },
  {
    id: "male_heart_emperor",
    title: "Heart Emperor",
    category: "premium",
    previewEmoji: "💝",
    iconKey: "heart-box",
    description: "Send 1,000 premium gifts",
    points: 300,
    requirementType: "gifts",
    requirementValue: 1000,
    sortOrder: 49,
  },
  {
    id: "male_call_sovereign",
    title: "Call Sovereign",
    category: "premium",
    previewEmoji: "🦁",
    iconKey: "account-star",
    description: "Make 2,500 premium calls",
    points: 310,
    requirementType: "calls",
    requirementValue: 2500,
    sortOrder: 50,
  },
  {
    id: "male_velvet_voice",
    title: "Velvet Voice",
    category: "premium",
    previewEmoji: "🔮",
    iconKey: "crystal-ball",
    description: "Spend 10,000 premium call minutes",
    points: 280,
    requirementType: "minutes",
    requirementValue: 10000,
    sortOrder: 51,
  },
  {
    id: "male_platinum_whale",
    title: "Platinum Whale",
    category: "premium",
    previewEmoji: "🐋",
    iconKey: "diamond-stone",
    description: "Complete 50 recharges",
    points: 270,
    requirementType: "recharges",
    requirementValue: 50,
    sortOrder: 52,
  },
  {
    id: "male_peacock_royale",
    title: "Peacock Royale",
    category: "premium",
    previewEmoji: "🦚",
    iconKey: "feather",
    description: "Add 100 creators to favorites",
    points: 290,
    requirementType: "favorites",
    requirementValue: 100,
    sortOrder: 53,
  },
  {
    id: "male_aurora_king",
    title: "Aurora King",
    category: "premium",
    previewEmoji: "🌌",
    iconKey: "weather-night-partly-cloudy",
    description: "Reach level 25",
    points: 350,
    requirementType: "level",
    requirementValue: 25,
    sortOrder: 54,
  },
  {
    id: "male_gilded_star",
    title: "Gilded Star",
    category: "premium",
    previewEmoji: "🌟",
    iconKey: "star-four-points",
    description: "Spend 500,000 gold on calls",
    points: 400,
    requirementType: "gold_spent",
    requirementValue: 500000,
    sortOrder: 55,
  },
  {
    id: "male_lion_palace",
    title: "Lion Palace",
    category: "premium",
    previewEmoji: "🏰",
    iconKey: "castle",
    description: "Make 5,000 calls",
    points: 360,
    requirementType: "calls",
    requirementValue: 5000,
    sortOrder: 56,
  },
  {
    id: "male_phoenix_vip",
    title: "Phoenix VIP",
    category: "premium",
    previewEmoji: "🔥",
    iconKey: "fire",
    description: "Complete 100 recharges",
    points: 380,
    requirementType: "recharges",
    requirementValue: 100,
    sortOrder: 57,
  },
  {
    id: "male_crystal_oracle",
    title: "Crystal Oracle",
    category: "premium",
    previewEmoji: "🪞",
    iconKey: "mirror",
    description: "Spend 20,000 call minutes",
    points: 340,
    requirementType: "minutes",
    requirementValue: 20000,
    sortOrder: 58,
  },
];

export const MAX_WORN_MALE_ACHIEVEMENT_BADGES = 3;
